export const countriesAndCurrencies = {
    'AFGHANISTAN': 'Afghani',
    'ÅLAND ISLANDS': 'Euro',
    'ALBANIA': 'Lek',
    'ALGERIA': 'Algerian Dinar',
    'AMERICAN SAMOA': 'US Dollar',
    'ANDORRA': 'Euro',
    'ANGOLA': 'Kwanza',
    'ANGUILLA': 'East Caribbean Dollar',
    'ANTARCTICA': 'No universal currency',
    'ANTIGUA AND BARBUDA': 'East Caribbean Dollar',
    'ARGENTINA': 'Argentine Peso',
    'ARMENIA': 'Armenian Dram',
    'ARUBA': 'Aruban Florin',
    'AUSTRALIA': 'Australian Dollar',
    'AUSTRIA': 'Euro',
    'AZERBAIJAN': 'Azerbaijanian Manat',
    'BAHAMAS (THE)': 'Bahamian Dollar',
    'BAHRAIN': 'Bahraini Dinar',
    'BANGLADESH': 'Taka',
    'BARBADOS': 'Barbados Dollar',
    'BELARUS': 'Belarussian Ruble',
    'BELGIUM': 'Euro',
    'BELIZE': 'Belize Dollar',
    'BENIN': 'CFA Franc BCEAO',
    'BERMUDA': 'Bermudian Dollar',
    'BHUTAN': 'Ngultrum',
    'BOLIVIA (PLURINATIONAL STATE OF)': 'Boliviano',
    'BONAIRE, SINT EUSTATIUS AND SABA': 'US Dollar',
    'BOSNIA AND HERZEGOVINA': 'Convertible Mark',
    'BOTSWANA': 'Pula',
    'BOUVET ISLAND': 'Norwegian Krone',
    'BRAZIL': 'Brazilian Real',
    'BRITISH INDIAN OCEAN TERRITORY (THE)': 'US Dollar',
    'BRUNEI DARUSSALAM': 'Brunei Dollar',
    'BULGARIA': 'Bulgarian Lev',
    'BURKINA FASO': 'CFA Franc BCEAO',
    'BURUNDI': 'Burundi Franc',
    'CABO VERDE': 'Cabo Verde Escudo',
    'CAMBODIA': 'Riel',
    'CAMEROON': 'CFA Franc BEAC',
    'CANADA': 'Canadian Dollar',
    'CAYMAN ISLANDS (THE)': 'Cayman Islands Dollar',
    'CENTRAL AFRICAN REPUBLIC (THE)': 'CFA Franc BEAC',
    'CHAD': 'CFA Franc BEAC',
    'CHILE': 'Chilean Peso',
    'CHINA': 'Yuan Renminbi',
    'CHRISTMAS ISLAND': 'Australian Dollar',
    'COCOS (KEELING) ISLANDS (THE)': 'Australian Dollar',
    'COLOMBIA': 'Colombian Peso',
    'COMOROS (THE)': 'Comoro Franc',
    'CONGO (THE DEMOCRATIC REPUBLIC OF THE)': 'Congolese Franc',
    'CONGO (THE)': 'CFA Franc BEAC',
    'COOK ISLANDS (THE)': 'New Zealand Dollar',
    'COSTA RICA': 'Costa Rican Colon',
    'CÔTE D\'IVOIRE': 'CFA Franc BCEAO',
    'CROATIA': 'Kuna',
    'CUBA': 'Cuban Peso',
    'CURAÇAO': 'Netherlands Antillean Guilder',
    'CYPRUS': 'Euro',
    'CZECH REPUBLIC (THE)': 'Czech Koruna',
    'DENMARK': 'Danish Krone',
    'DJIBOUTI': 'Djibouti Franc',
    'DOMINICA': 'East Caribbean Dollar',
    'DOMINICAN REPUBLIC (THE)': 'Dominican Peso',
    'ECUADOR': 'US Dollar',
    'EGYPT': 'Egyptian Pound',
    'EL SALVADOR': 'US Dollar',
    'EQUATORIAL GUINEA': 'CFA Franc BEAC',
    'ERITREA': 'Nakfa',
    'ESTONIA': 'Euro',
    'ETHIOPIA': 'Ethiopian Birr',
    'EUROPEAN UNION': 'Euro',
    'FALKLAND ISLANDS (THE) [MALVINAS]': 'Falkland Islands Pound',
    'FAROE ISLANDS (THE)': 'Danish Krone',
    'FIJI': 'Fiji Dollar',
    'FINLAND': 'Euro',
    'FRANCE': 'Euro',
    'FRENCH GUIANA': 'Euro',
    'FRENCH POLYNESIA': 'CFP Franc',
    'FRENCH SOUTHERN TERRITORIES (THE)': 'Euro',
    'GABON': 'CFA Franc BEAC',
    'GAMBIA (THE)': 'Dalasi',
    'GEORGIA': 'Lari',
    'GERMANY': 'Euro',
    'GHANA': 'Ghana Cedi',
    'GIBRALTAR': 'Gibraltar Pound',
    'GREECE': 'Euro',
    'GREENLAND': 'Danish Krone',
    'GRENADA': 'East Caribbean Dollar',
    'GUADELOUPE': 'Euro',
    'GUAM': 'US Dollar',
    'GUATEMALA': 'Quetzal',
    'GUERNSEY': 'Pound Sterling',
    'GUINEA': 'Guinea Franc',
    'GUINEA-BISSAU': 'CFA Franc BCEAO',
    'GUYANA': 'Guyana Dollar',
    'HAITI': 'Gourde',
    'HEARD ISLAND AND McDONALD ISLANDS': 'Australian Dollar',
    'HOLY SEE (THE)': 'Euro',
    'HONDURAS': 'Lempira',
    'HONG KONG': 'Hong Kong Dollar',
    'HUNGARY': 'Forint',
    'ICELAND': 'Iceland Krona',
    'INDIA': 'Indian Rupee',
    'INDONESIA': 'Rupiah',
    'INTERNATIONAL MONETARY FUND (IMF) ': 'SDR (Special Drawing Right)',
    'IRAN (ISLAMIC REPUBLIC OF)': 'Iranian Rial',
    'IRAQ': 'Iraqi Dinar',
    'IRELAND': 'Euro',
    'ISLE OF MAN': 'Pound Sterling',
    'ISRAEL': 'New Israeli Sheqel',
    'ITALY': 'Euro',
    'JAMAICA': 'Jamaican Dollar',
    'JAPAN': 'Yen',
    'JERSEY': 'Pound Sterling',
    'JORDAN': 'Jordanian Dinar',
    'KAZAKHSTAN': 'Tenge',
    'KENYA': 'Kenyan Shilling',
    'KIRIBATI': 'Australian Dollar',
    'KOREA (THE DEMOCRATIC PEOPLE\'S REPUBLIC OF)': 'North Korean Won',
    'KOREA (THE REPUBLIC OF)': 'Won',
    'KUWAIT': 'Kuwaiti Dinar',
    'KYRGYZSTAN': 'Som',
    'LAO PEOPLE\'S DEMOCRATIC REPUBLIC (THE)': 'Kip',
    'LATVIA': 'Euro',
    'LEBANON': 'Lebanese Pound',
    'LESOTHO': 'Loti',
    'LIBERIA': 'Liberian Dollar',
    'LIBYA': 'Libyan Dinar',
    'LIECHTENSTEIN': 'Swiss Franc',
    'LITHUANIA': 'Euro',
    'LUXEMBOURG': 'Euro',
    'MACAO': 'Pataca',
    'REPUBLIC OF NORTH MACEDONIA': 'Denar',
    'MADAGASCAR': 'Malagasy Ariary',
    'MALAWI': 'Kwacha',
    'MALAYSIA': 'Malaysian Ringgit',
    'MALDIVES': 'Rufiyaa',
    'MALI': 'CFA Franc BCEAO',
    'MALTA': 'Euro',
    'MARSHALL ISLANDS (THE)': 'US Dollar',
    'MARTINIQUE': 'Euro',
    'MAURITANIA': 'Ouguiya',
    'MAURITIUS': 'Mauritius Rupee',
    'MAYOTTE': 'Euro',
    'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP': 'ADB Unit of Account',
    'MEXICO': 'Mexican Peso',
    'MICRONESIA (FEDERATED STATES OF)': 'US Dollar',
    'MOLDOVA (THE REPUBLIC OF)': 'Moldovan Leu',
    'MONACO': 'Euro',
    'MONGOLIA': 'Tugrik',
    'MONTENEGRO': 'Euro',
    'MONTSERRAT': 'East Caribbean Dollar',
    'MOROCCO': 'Moroccan Dirham',
    'MOZAMBIQUE': 'Mozambique Metical',
    'MYANMAR': 'Kyat',
    'NAMIBIA': 'Namibia Dollar',
    'NAURU': 'Australian Dollar',
    'NEPAL': 'Nepalese Rupee',
    'NETHERLANDS (THE)': 'Euro',
    'NEW CALEDONIA': 'CFP Franc',
    'NEW ZEALAND': 'New Zealand Dollar',
    'NICARAGUA': 'Cordoba Oro',
    'NIGER (THE)': 'CFA Franc BCEAO',
    'NIGERIA': 'Naira',
    'NIUE': 'New Zealand Dollar',
    'NORFOLK ISLAND': 'Australian Dollar',
    'NORTHERN MARIANA ISLANDS (THE)': 'US Dollar',
    'NORWAY': 'Norwegian Krone',
    'OMAN': 'Rial Omani',
    'PAKISTAN': 'Pakistan Rupee',
    'PALAU': 'US Dollar',
    'PALESTINE, STATE OF': 'No universal currency',
    'PANAMA': 'Balboa',
    'PAPUA NEW GUINEA': 'Kina',
    'PARAGUAY': 'Guarani',
    'PERU': 'Nuevo Sol',
    'PHILIPPINES (THE)': 'Philippine Peso',
    'PITCAIRN': 'New Zealand Dollar',
    'POLAND': 'Zloty',
    'PORTUGAL': 'Euro',
    'PUERTO RICO': 'US Dollar',
    'QATAR': 'Qatari Rial',
    'RÉUNION': 'Euro',
    'ROMANIA': 'Romanian Leu',
    'RUSSIAN FEDERATION (THE)': 'Russian Ruble',
    'RWANDA': 'Rwanda Franc',
    'SAINT BARTHÉLEMY': 'Euro',
    'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA': 'Saint Helena Pound',
    'SAINT KITTS AND NEVIS': 'East Caribbean Dollar',
    'SAINT LUCIA': 'East Caribbean Dollar',
    'SAINT MARTIN (FRENCH PART)': 'Euro',
    'SAINT PIERRE AND MIQUELON': 'Euro',
    'SAINT VINCENT AND THE GRENADINES': 'East Caribbean Dollar',
    'SAMOA': 'Tala',
    'SAN MARINO': 'Euro',
    'SAO TOME AND PRINCIPE': 'Dobra',
    'SAUDI ARABIA': 'Saudi Riyal',
    'SENEGAL': 'CFA Franc BCEAO',
    'SERBIA': 'Serbian Dinar',
    'SEYCHELLES': 'Seychelles Rupee',
    'SIERRA LEONE': 'Leone',
    'SINGAPORE': 'Singapore Dollar',
    'SINT MAARTEN (DUTCH PART)': 'Netherlands Antillean Guilder',
    'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"': 'Sucre',
    'SLOVAKIA': 'Euro',
    'SLOVENIA': 'Euro',
    'SOLOMON ISLANDS': 'Solomon Islands Dollar',
    'SOMALIA': 'Somali Shilling',
    'SOUTH AFRICA': 'Rand',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'No universal currency',
    'SOUTH SUDAN': 'South Sudanese Pound',
    'SPAIN': 'Euro',
    'SRI LANKA': 'Sri Lanka Rupee',
    'SUDAN (THE)': 'Sudanese Pound',
    'SURINAME': 'Surinam Dollar',
    'SVALBARD AND JAN MAYEN': 'Norwegian Krone',
    'SWAZILAND': 'Lilangeni',
    'SWEDEN': 'Swedish Krona',
    'SWITZERLAND': 'Swiss Franc',
    'SYRIAN ARAB REPUBLIC': 'Syrian Pound',
    'TAIWAN (PROVINCE OF CHINA)': 'New Taiwan Dollar',
    'TAJIKISTAN': 'Somoni',
    'TANZANIA, UNITED REPUBLIC OF': 'Tanzanian Shilling',
    'THAILAND': 'Baht',
    'TIMOR-LESTE': 'US Dollar',
    'TOGO': 'CFA Franc BCEAO',
    'TOKELAU': 'New Zealand Dollar',
    'TONGA': 'Pa’anga',
    'TRINIDAD AND TOBAGO': 'Trinidad and Tobago Dollar',
    'TUNISIA': 'Tunisian Dinar',
    'TURKEY': 'Turkish Lira',
    'TURKMENISTAN': 'Turkmenistan New Manat',
    'TURKS AND CAICOS ISLANDS (THE)': 'US Dollar',
    'TUVALU': 'Australian Dollar',
    'UGANDA': 'Uganda Shilling',
    'UKRAINE': 'Hryvnia',
    'UNITED ARAB EMIRATES (THE)': 'UAE Dirham',
    'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)': 'Pound Sterling',
    'UNITED STATES MINOR OUTLYING ISLANDS (THE)': 'US Dollar',
    'UNITED STATES OF AMERICA (THE)': 'US Dollar',
    'URUGUAY': 'Peso Uruguayo',
    'UZBEKISTAN': 'Uzbekistan Sum',
    'VANUATU': 'Vatu',
    'VENEZUELA (BOLIVARIAN REPUBLIC OF)': 'Bolivar',
    'VIET NAM': 'Dong',
    'VIRGIN ISLANDS (BRITISH)': 'US Dollar',
    'VIRGIN ISLANDS (U.S.)': 'US Dollar',
    'WALLIS AND FUTUNA': 'CFP Franc',
    'WESTERN SAHARA': 'Moroccan Dirham',
    'YEMEN': 'Yemeni Rial',
    'ZAMBIA': 'Zambian Kwacha',
    'ZIMBABWE': 'Zimbabwe Dollar',
}