export const currencyNamesAndCodes = {
    'Afghani': 'AFN',
    'Euro': 'EUR',
    'Lek': 'ALL',
    'Algerian Dinar': 'DZD',
    'US Dollar': 'USD',
    'Kwanza': 'AOA',
    'East Caribbean Dollar': 'XCD',
    'No universal currency': '',
    'Argentine Peso': 'ARS',
    'Armenian Dram': 'AMD',
    'Aruban Florin': 'AWG',
    'Australian Dollar': 'AUD',
    'Azerbaijanian Manat': 'AZN',
    'Bahamian Dollar': 'BSD',
    'Bahraini Dinar': 'BHD',
    'Taka': 'BDT',
    'Barbados Dollar': 'BBD',
    'Belarussian Ruble': 'BYN',
    'Belize Dollar': 'BZD',
    'CFA Franc BCEAO': 'XOF',
    'Bermudian Dollar': 'BMD',
    'Ngultrum': 'BTN',
    'Indian Rupee': 'INR',
    'Boliviano': 'BOB',
    'Mvdol': 'BOV',
    'Convertible Mark': 'BAM',
    'Pula': 'BWP',
    'Norwegian Krone': 'NOK',
    'Brazilian Real': 'BRL',
    'Brunei Dollar': 'BND',
    'Bulgarian Lev': 'BGN',
    'Burundi Franc': 'BIF',
    'Cabo Verde Escudo': 'CVE',
    'Riel': 'KHR',
    'CFA Franc BEAC': 'XAF',
    'Canadian Dollar': 'CAD',
    'Cayman Islands Dollar': 'KYD',
    'Unidad de Fomento': 'CLF',
    'Chilean Peso': 'CLP',
    'Yuan Renminbi': 'CNY',
    'Colombian Peso': 'COP',
    'Unidad de Valor Real': 'COU',
    'Comoro Franc': 'KMF',
    'Congolese Franc': 'CDF',
    'New Zealand Dollar': 'NZD',
    'Costa Rican Colon': 'CRC',
    'Kuna': 'HRK',
    'Peso Convertible': 'CUC',
    'Cuban Peso': 'CUP',
    'Netherlands Antillean Guilder': 'ANG',
    'Czech Koruna': 'CZK',
    'Danish Krone': 'DKK',
    'Djibouti Franc': 'DJF',
    'Dominican Peso': 'DOP',
    'Egyptian Pound': 'EGP',
    'El Salvador Colon': 'SVC',
    'Nakfa': 'ERN',
    'Ethiopian Birr': 'ETB',
    'Falkland Islands Pound': 'FKP',
    'Fiji Dollar': 'FJD',
    'CFP Franc': 'XPF',
    'Dalasi': 'GMD',
    'Lari': 'GEL',
    'Ghana Cedi': 'GHS',
    'Gibraltar Pound': 'GIP',
    'Quetzal': 'GTQ',
    'Pound Sterling': 'GBP',
    'Guinea Franc': 'GNF',
    'Guyana Dollar': 'GYD',
    'Gourde': 'HTG',
    'Lempira': 'HNL',
    'Hong Kong Dollar': 'HKD',
    'Forint': 'HUF',
    'Iceland Krona': 'ISK',
    'Rupiah': 'IDR',
    'SDR (Special Drawing Right)': 'XDR',
    'Iranian Rial': 'IRR',
    'Iraqi Dinar': 'IQD',
    'New Israeli Sheqel': 'ILS',
    'Jamaican Dollar': 'JMD',
    'Yen': 'JPY',
    'Jordanian Dinar': 'JOD',
    'Tenge': 'KZT',
    'Kenyan Shilling': 'KES',
    'North Korean Won': 'KPW',
    'Won': 'KRW',
    'Kuwaiti Dinar': 'KWD',
    'Som': 'KGS',
    'Kip': 'LAK',
    'Lebanese Pound': 'LBP',
    'Loti': 'LSL',
    'Rand': 'ZAR',
    'Liberian Dollar': 'LRD',
    'Libyan Dinar': 'LYD',
    'Swiss Franc': 'CHF',
    'Pataca': 'MOP',
    'Denar': 'MKD',
    'Malagasy Ariary': 'MGA',
    'Kwacha': 'MWK',
    'Malaysian Ringgit': 'MYR',
    'Rufiyaa': 'MVR',
    'Ouguiya': 'MRU',
    'Mauritius Rupee': 'MUR',
    'ADB Unit of Account': 'XUA',
    'Mexican Peso': 'MXN',
    'Mexican Unidad de Inversion (UDI)': 'MXV',
    'Moldovan Leu': 'MDL',
    'Tugrik': 'MNT',
    'Moroccan Dirham': 'MAD',
    'Mozambique Metical': 'MZN',
    'Kyat': 'MMK',
    'Namibia Dollar': 'NAD',
    'Nepalese Rupee': 'NPR',
    'Cordoba Oro': 'NIO',
    'Naira': 'NGN',
    'Rial Omani': 'OMR',
    'Pakistan Rupee': 'PKR',
    'Balboa': 'PAB',
    'Kina': 'PGK',
    'Guarani': 'PYG',
    'Nuevo Sol': 'PEN',
    'Philippine Peso': 'PHP',
    'Zloty': 'PLN',
    'Qatari Rial': 'QAR',
    'Romanian Leu': 'RON',
    'Russian Ruble': 'RUB',
    'Rwanda Franc': 'RWF',
    'Saint Helena Pound': 'SHP',
    'Tala': 'WST',
    'Dobra': 'STN',
    'Saudi Riyal': 'SAR',
    'Serbian Dinar': 'RSD',
    'Seychelles Rupee': 'SCR',
    'Leone': 'SLE',
    'Singapore Dollar': 'SGD',
    'Sucre': 'XSU',
    'Solomon Islands Dollar': 'SBD',
    'Somali Shilling': 'SOS',
    'South Sudanese Pound': 'SSP',
    'Sri Lanka Rupee': 'LKR',
    'Sudanese Pound': 'SDG',
    'Surinam Dollar': 'SRD',
    'Lilangeni': 'SZL',
    'Swedish Krona': 'SEK',
    'WIR Euro': 'CHE',
    'WIR Franc': 'CHW',
    'Syrian Pound': 'SYP',
    'New Taiwan Dollar': 'TWD',
    'Somoni': 'TJS',
    'Tanzanian Shilling': 'TZS',
    'Baht': 'THB',
    'Pa’anga': 'TOP',
    'Trinidad and Tobago Dollar': 'TTD',
    'Tunisian Dinar': 'TND',
    'Turkish Lira': 'TRY',
    'Turkmenistan New Manat': 'TMT',
    'Uganda Shilling': 'UGX',
    'Hryvnia': 'UAH',
    'UAE Dirham': 'AED',
    'US Dollar (Next day)': 'USN',
    'Uruguay Peso en Unidades Indexadas (URUIURUI)': 'UYI',
    'Peso Uruguayo': 'UYU',
    'Uzbekistan Sum': 'UZS',
    'Vatu': 'VUV',
    'Bolivar': 'VEF',
    'Dong': 'VND',
    'Yemeni Rial': 'YER',
    'Zambian Kwacha': 'ZMW',
    'Zimbabwe Dollar': 'ZWL',
}